### PR TITLE
Fixed statsmodels Compatibility support and Path Variables

### PR DESCRIPTION
**Pull request by ghostaccount737**
- Fixed Path Variables
- Porting `multipletests` function  from `statsmodels` to fix compatibility for Python2

### CODE REVIEW

**Comment by PVinay737** [comment]
@benfulcher @chlubba Any feedback regarding the changes ?

**Comment by benfulcher** [comment]
Thanks @PVinay737! Sorry for the delay—I'm on leave at the moment but I will get someone to take a look through soon

**Comment by ghostaccount737** [comment]
Just suggesting some possible changes..

**Comment by benfulcher** [comment]
Thanks @ppal4396 for checking—will merge

**Pull request merged**
